To-do App
julie-ify/react-todo-app pull request #1
Opened 2021-09-19 16:55 UTC by julie-ify

In this milestone, I created a to-dos App using React following a [React Tutorial From Scratch: A Step-by-Step Guide (2021)](https://ibaslogic.com/react-tutorial-for-beginners/)

2021-09-21 09:46 UTC, ShinobiWarior requested changes
Hi @julie-ify 👋🏼  ,

Good job so far!

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required changes ♻️ 

Please check the comments below for the changes required . 👇🏼 

## Optional suggestions

Also, you can find optional changes marked with the prefix [Optional].

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-09-21 09:46 UTC, ShinobiWarior commented on src/classBased/components/TodosList.js
> +  const { deleteTodoProps } = props;
[Required]
Keep code DRY. Instead of defining all variables in separate lines, you could do it at once:
`const { .., .., .., } = props`

2021-09-21 09:46 UTC, ShinobiWarior commented on src/functionBased/components/InputTodo.js
> +  });
[Required]
Instead of using inputText and setInputText, it will be better if you use title and setTitle directly in your hook. 
`const[title, setTitle] = useState('');`

Make sure that you refactor the rest of the code as well.

2021-09-21 09:46 UTC, ShinobiWarior commented on src/functionBased/components/InputTodo.js
> +
[Optional]
You can remove this comment and add:
```
import PropTypes from 'prop-types';

...

MyComponent.propTypes = {
  children: PropTypes.element.isRequired
};
```
and run: 
`npm install --save prop-types`

2021-09-21 09:46 UTC, ShinobiWarior commented on src/functionBased/components/TodoItem.js
> +/* eslint-disable react/prop-types */
[Optional]
You can remove this comment and add:
```
import PropTypes from 'prop-types';

...

MyComponent.propTypes = {
  children: PropTypes.element.isRequired
};
```
and run: 
`npm install --save prop-types`

2021-09-21 09:46 UTC, ShinobiWarior commented on src/functionBased/components/TodosList.js
> +
[Optional]
You can remove this comment and add:
```
import PropTypes from 'prop-types';

...

MyComponent.propTypes = {
  children: PropTypes.element.isRequired
};
```
and run: 
`npm install --save prop-types`

2021-09-21 15:57 UTC, julie-ify commented on src/functionBased/components/InputTodo.js
> +  });
Ok.

2021-09-21 15:57 UTC, julie-ify commented on src/classBased/components/TodosList.js
> +  const { deleteTodoProps } = props;
Ok, Thanks

2021-09-22 07:47 UTC, ShinobiWarior approved these changes
## Congratulations! 🎉🎉  
### Hi @julie-ify ,

Your project is complete! ✅ ✅ ✅ There is nothing else to say other than... it's time to merge it !!
Congratulations! 🎉
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-09-22 18:59 UTC, merged